/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import models.Cliente;
import models.PessoaFisica;
import models.PessoaJuridica;
import singleton.Storage;
import tablemodel.ClienteTableModel;
import tablemodel.ProdutoTableModel;

/**
 *
 * @author danie
 */
public class FrmClientes extends javax.swing.JFrame {
    
    public Storage storage;
    private ClienteTableModel clienteModel;
    private int id_cliente;

    /**
     * Creates new form FrmClientes
     */
    public FrmClientes() {
        initComponents();
        this.jPnlPessoaJuridica.setVisible(false);
    }
    
    public void initTable(){
        clienteModel = new ClienteTableModel((ArrayList<Cliente>) this.storage.clientes);
        jTblClientes.setModel(clienteModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblCidade = new javax.swing.JLabel();
        jTxtCidade = new javax.swing.JTextField();
        jLblFone = new javax.swing.JLabel();
        jTxtTelefone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTxtEndereco = new javax.swing.JTextField();
        jCmbPessoaTipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPnlPessoaFisica = new javax.swing.JPanel();
        jLblPessoaFisicaNome = new javax.swing.JLabel();
        jTxtPessoaFisicaNome = new javax.swing.JTextField();
        jLblPessoaFisicaCPF = new javax.swing.JLabel();
        jTxtPessoaFisicaCpf = new javax.swing.JTextField();
        jPnlPessoaJuridica = new javax.swing.JPanel();
        jTxtPessoaJuricaNome = new javax.swing.JTextField();
        jLblPessoaFisicaCPF1 = new javax.swing.JLabel();
        jTxtPessoaJuridicaCnpj = new javax.swing.JTextField();
        jLblPessoaFisicaNome1 = new javax.swing.JLabel();
        jBtnAdicionar = new javax.swing.JButton();
        jBtnSalvar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblCidade.setText("Cidade:");

        jLblFone.setText("Telefone:");

        jTxtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTelefoneActionPerformed(evt);
            }
        });

        jLabel1.setText("Endereço:");

        jCmbPessoaTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pessoa Física", "Pessoa Jurídica" }));
        jCmbPessoaTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCmbPessoaTipoItemStateChanged(evt);
            }
        });
        jCmbPessoaTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCmbPessoaTipoMouseClicked(evt);
            }
        });
        jCmbPessoaTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbPessoaTipoActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo:");

        jLblPessoaFisicaNome.setText("Nome:");

        jLblPessoaFisicaCPF.setText("CPF:");

        javax.swing.GroupLayout jPnlPessoaFisicaLayout = new javax.swing.GroupLayout(jPnlPessoaFisica);
        jPnlPessoaFisica.setLayout(jPnlPessoaFisicaLayout);
        jPnlPessoaFisicaLayout.setHorizontalGroup(
            jPnlPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlPessoaFisicaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblPessoaFisicaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtPessoaFisicaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblPessoaFisicaCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtPessoaFisicaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPnlPessoaFisicaLayout.setVerticalGroup(
            jPnlPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlPessoaFisicaLayout.createSequentialGroup()
                .addGroup(jPnlPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblPessoaFisicaNome)
                    .addComponent(jTxtPessoaFisicaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtPessoaFisicaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblPessoaFisicaCPF))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jPnlPessoaJuridica.setEnabled(false);

        jLblPessoaFisicaCPF1.setText("CNPJ:");

        jLblPessoaFisicaNome1.setText("Razão Social:");

        javax.swing.GroupLayout jPnlPessoaJuridicaLayout = new javax.swing.GroupLayout(jPnlPessoaJuridica);
        jPnlPessoaJuridica.setLayout(jPnlPessoaJuridicaLayout);
        jPnlPessoaJuridicaLayout.setHorizontalGroup(
            jPnlPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlPessoaJuridicaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblPessoaFisicaNome1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtPessoaJuricaNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblPessoaFisicaCPF1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtPessoaJuridicaCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPnlPessoaJuridicaLayout.setVerticalGroup(
            jPnlPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlPessoaJuridicaLayout.createSequentialGroup()
                .addGroup(jPnlPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtPessoaJuricaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtPessoaJuridicaCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblPessoaFisicaCPF1)
                    .addComponent(jLblPessoaFisicaNome1))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jBtnAdicionar.setText("Adicionar");
        jBtnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAdicionarActionPerformed(evt);
            }
        });

        jBtnSalvar.setText("Salvar");
        jBtnSalvar.setEnabled(false);
        jBtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarActionPerformed(evt);
            }
        });

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnExcluir.setText("Excluir");
        jBtnExcluir.setEnabled(false);
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jTblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPnlPessoaFisica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPnlPessoaJuridica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLblFone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCmbPessoaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtEndereco))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 4, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCidade)
                    .addComponent(jTxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblFone)
                    .addComponent(jTxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCmbPessoaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnlPessoaFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnlPessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAdicionar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnSalvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTelefoneActionPerformed

    private void jCmbPessoaTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCmbPessoaTipoItemStateChanged

    }//GEN-LAST:event_jCmbPessoaTipoItemStateChanged

    private void jCmbPessoaTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCmbPessoaTipoMouseClicked
        
    }//GEN-LAST:event_jCmbPessoaTipoMouseClicked

    private void jCmbPessoaTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbPessoaTipoActionPerformed
        if(this.jCmbPessoaTipo.getSelectedIndex() == 0){
            
                this.jPnlPessoaFisica.setVisible(true);
                this.jPnlPessoaJuridica.setVisible(false);
        }else{
            this.jPnlPessoaFisica.setVisible(false);
                this.jPnlPessoaJuridica.setVisible(true);
             
        }
    }//GEN-LAST:event_jCmbPessoaTipoActionPerformed

    private void jBtnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAdicionarActionPerformed
        String cidade = this.jTxtCidade.getText();
        String fone = this.jTxtTelefone.getText();
        String endereco = this.jTxtEndereco.getText();
        String nome,codigo;
        Cliente cliente;
        if(this.jCmbPessoaTipo.getSelectedIndex() == 0){
            nome = this.jTxtPessoaFisicaNome.getText();
            codigo = this.jTxtPessoaFisicaCpf.getText();
            cliente = new PessoaFisica(codigo,nome,cidade,endereco,fone);
        }else{
            nome = this.jTxtPessoaJuricaNome.getText();
            codigo = this.jTxtPessoaJuridicaCnpj.getText();
            cliente = new PessoaJuridica(codigo,nome,cidade,endereco,fone);
        }
        this.storage.clientes.add(cliente);
        this.clienteModel.fireTableDataChanged();
        this.limpaCampos();
    }//GEN-LAST:event_jBtnAdicionarActionPerformed

    private void jBtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarActionPerformed
        Cliente cliente = this.clienteModel.getCliente(this.id_cliente);
        cliente.setCidade(this.jTxtCidade.getText());
        cliente.setFone(this.jTxtTelefone.getText());
        cliente.setEndereco(this.jTxtEndereco.getText());
        String nome,codigo;
        if(this.jCmbPessoaTipo.getSelectedIndex() == 0){
            nome = this.jTxtPessoaFisicaNome.getText();
            codigo = this.jTxtPessoaFisicaCpf.getText();            
        }else{
            nome = this.jTxtPessoaJuricaNome.getText();
            codigo = this.jTxtPessoaJuridicaCnpj.getText();                         
        }
        cliente.setNome(nome);
        cliente.setCodigo(codigo);
        this.limpaCampos();
        this.clienteModel.fireTableDataChanged();
    }//GEN-LAST:event_jBtnSalvarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        this.limpaCampos();
        this.jBtnAdicionar.setEnabled(true);
        this.jBtnSalvar.setEnabled(false);
        this.jBtnExcluir.setEnabled(false);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        this.storage.clientes.remove(this.id_cliente);
        this.limpaCampos();
        this.clienteModel.fireTableDataChanged();
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jTblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblClientesMouseClicked
        this.jBtnAdicionar.setEnabled(false);
        this.jBtnExcluir.setEnabled(true);
        this.jBtnSalvar.setEnabled(true);
        this.id_cliente = this.jTblClientes.getSelectedRow();
        Cliente cliente = this.clienteModel.getCliente(this.id_cliente);
        this.jTxtCidade.setText(cliente.getCidade());
        this.jTxtEndereco.setText(cliente.getEndereco());
        this.jTxtTelefone.setText(cliente.getFone());
        if(cliente instanceof PessoaFisica){
            this.jPnlPessoaFisica.setVisible(true);
            this.jPnlPessoaJuridica.setVisible(false);
            this.jCmbPessoaTipo.setSelectedIndex(0);
            this.jTxtPessoaFisicaNome.setText(cliente.getNome());
            this.jTxtPessoaFisicaCpf.setText(cliente.getCodigo());
        }else if(cliente instanceof PessoaJuridica){
            this.jPnlPessoaFisica.setVisible(false);
            this.jPnlPessoaJuridica.setVisible(true);
            this.jCmbPessoaTipo.setSelectedIndex(1);
            this.jTxtPessoaJuricaNome.setText(cliente.getNome());
            this.jTxtPessoaJuridicaCnpj.setText(cliente.getCodigo());
        }
        this.jCmbPessoaTipo.setEnabled(false);
    }//GEN-LAST:event_jTblClientesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdicionar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnSalvar;
    private javax.swing.JComboBox<String> jCmbPessoaTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLblCidade;
    private javax.swing.JLabel jLblFone;
    private javax.swing.JLabel jLblPessoaFisicaCPF;
    private javax.swing.JLabel jLblPessoaFisicaCPF1;
    private javax.swing.JLabel jLblPessoaFisicaNome;
    private javax.swing.JLabel jLblPessoaFisicaNome1;
    private javax.swing.JPanel jPnlPessoaFisica;
    private javax.swing.JPanel jPnlPessoaJuridica;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTblClientes;
    private javax.swing.JTextField jTxtCidade;
    private javax.swing.JTextField jTxtEndereco;
    private javax.swing.JTextField jTxtPessoaFisicaCpf;
    private javax.swing.JTextField jTxtPessoaFisicaNome;
    private javax.swing.JTextField jTxtPessoaJuricaNome;
    private javax.swing.JTextField jTxtPessoaJuridicaCnpj;
    private javax.swing.JTextField jTxtTelefone;
    // End of variables declaration//GEN-END:variables

    private void limpaCampos() {
        this.id_cliente = -1;
        this.jTxtCidade.setText("");
        this.jTxtTelefone.setText("");
        this.jCmbPessoaTipo.setSelectedIndex(0);
        this.jTxtEndereco.setText("");
        this.jTxtPessoaFisicaNome.setText("");
        this.jTxtPessoaFisicaCpf.setText("");
        this.jTxtPessoaJuricaNome.setText("");
        this.jTxtPessoaJuridicaCnpj.setText("");
        this.jPnlPessoaFisica.setVisible(true);
        this.jPnlPessoaJuridica.setVisible(false);
        this.jCmbPessoaTipo.setEnabled(true);
    }
}
